version: "3"
services:
  webrtc-app:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PORT=5000
      # Add other environment variables as needed
    volumes:
      # For development, you can mount your code to enable hot reloading
      # - .:/usr/src/app
      # - /usr/src/app/node_modules
      # For production, comment out the above lines
